### ISSUE TITLE
table salesforce_contacts missing

### ISSUE THREAD

**Issue by amjo** [voycey/salesforce-datasource-cakephp-3.x#1]
Hello there,

first off thank you for this quick and slick easy-to-install plugin; however, it seems that the correct datasource is not being utilized although i am assigning SalesforceSource in the app/Config/database.php as datasource. i'm getting:

> Error: Table salesforce_contacts for model SalesforceContact was not found in datasource default.

am i missing anything? i'm sure i've followed all instructions on the readme. is it possible that the datasource variable name $sflive should be renamed to $_baseConfig? (first time i install a plugin on Cakephp 2.0 - im upgrading an existing cakephp site).

thanks,
/avz

**Comment by voycey** [comment]
Are you using the 2.x branch? 

Can you post your SalesforceContact model here?

**Comment by amjo** [comment]
yes, im using the 2.x branch for sure... i was about to update my issue for future reference to other users. i had to specify the plugin to which the datasource belongs to in the database.php file:

`	var $sflive = array(
            'datasource' => 'Salesforce.SalesforceSource', // this was the problem. i added "Salesforce."
            'standard_wsdl' => 'enterprise.wsdl.xml',
            'dynamic_mode' => false,
            'my_wsdl' => 'enterprise.wsdl.xml',//optional but recommended
            'username' => 'jbouchebl@eastlinemarketing.com',
            'password' => 'jbetw86dz2OAvKqoeSEZH637v4e2LM4D'
        );`

hope this is useful for others :)

**Comment by amjo** [comment]
yes, im using the 2.x branch for sure... i was about to update my issue for future reference to other users. i had to specify the plugin to which the datasource belongs to in the database.php file:

```
var $sflive = array(
'datasource' => 'Salesforce.SalesforceSource', // this was the problem. i added "Salesforce."
'standard_wsdl' => 'enterprise.wsdl.xml',
'dynamic_mode' => false,
'my_wsdl' => 'enterprise.wsdl.xml',//optional but recommended
'username' => '',
'password' => ''
);
```

hope this is useful for others :)

**Comment by voycey** [comment]
Ah yeah good spot! I have updated the readme for it! Thanks!
