### ISSUE TITLE
Help on TLS

### ISSUE THREAD

**Issue by InderjeetSohal** [voycey/salesforce-datasource-cakephp-3.x#3]
Hi Dan,

We need your help in solving TLS upgrading issue with CakePHP and Soap.

Does your CakePHP 2.x salesforce plugin is compatible with TLS 1.2? 

If yes then please let us know what are the other places where we need to make code change for upgrading TSL 1.0 to TLS 1.2

Thanks,
Inderjeet

**Comment by voycey** [comment]
Im not 100% sure but the soap library should handle this, the plugin only
sends requests to the endpoint defined in the WSDL which should be https!

Maybe check the Sforce php client to see if people are using it with TLS

**Comment by voycey** [comment]
Hi Inderjeet, 

Can you try the following please?

Update Line 133:

https://github.com/voycey/cakephp-salesforce/blob/2.x/Salesforce/Model/Datasource/SalesforceSource.php#L133

to 

```$mySoapClient = $mySforceConnection->createConnection($wsdl, null, array('ssl_method' => SOAP_SSL_METHOD_TLS));```

and let me know if this works (or submit a PR for it)
